
const KEY="scwis_final_req_v1";
const defaults=[
{id:"S1001",name:"Alex Chen",consent:true,lms:92,library:6,dining:14,gym:5,stress:2,sleep:7.4,social:8},
{id:"S1002",name:"Maya Lee",consent:true,lms:43,library:0,dining:4,gym:0,stress:4,sleep:4.2,social:2},
{id:"S1003",name:"Daniel Wong",consent:false,lms:76,library:3,dining:9,gym:2,stress:3,sleep:6.1,social:5},
{id:"S1004",name:"Sara Patel",consent:true,lms:38,library:1,dining:5,gym:1,stress:5,sleep:3.8,social:1},
{id:"S1005",name:"Ryan Smith",consent:true,lms:81,library:4,dining:10,gym:3,stress:2,sleep:6.9,social:6},
{id:"S1006",name:"Olivia Brown",consent:true,lms:67,library:2,dining:8,gym:1,stress:3,sleep:5.8,social:4}
];
const trend=[{w:"W1",s:44,b:78},{w:"W2",s:49,b:74},{w:"W3",s:55,b:69},{w:"W4",s:52,b:71},{w:"W5",s:46,b:76},{w:"W6",s:39,b:80}];
let state=load()||{students:defaults,cases:[],selectedId:defaults[0].id,logs:["System initialized","Consent filter active","Human-in-the-loop mode enabled"],settings:{high:80,medium:55}};
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch(e){return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function txt(id,v){let e=document.getElementById(id);if(e)e.textContent=v}
function log(m){state.logs.unshift(new Date().toLocaleTimeString()+" — "+m);state.logs=state.logs.slice(0,15);save();renderAll()}
function risk(s){if(!s.consent)return{score:null,level:"Blocked",tone:"blocked",reasons:["No consent: behavioral data excluded before analysis."]};let score=0,r=[];if(s.lms<50){score+=22;r.push("LMS activity decline")}if(s.dining<6){score+=18;r.push("Irregular dining pattern")}if(s.gym===0){score+=8;r.push("No physical activity record")}if(s.library<=1){score+=10;r.push("Library engagement decreased")}if(s.stress>=4){score+=22;r.push("High self-reported stress")}if(s.sleep<5){score+=18;r.push("Sleep below healthy range")}if(s.social<=2){score+=15;r.push("Possible social isolation")}score=Math.min(100,score);if(score>=state.settings.high)return{score,level:"High",tone:"high",reasons:r};if(score>=state.settings.medium)return{score,level:"Medium",tone:"medium",reasons:r};if(score>=30)return{score,level:"Low",tone:"low",reasons:r};return{score,level:"Balanced",tone:"balanced",reasons:["No major risk pattern detected"]}}
function data(){return state.students.map(s=>({...s,risk:risk(s)}))}
function sel(){return data().find(s=>s.id===state.selectedId)||data()[0]}
function cls(t){return t==="high"?"high":t==="medium"?"medium":t==="low"?"low":t==="blocked"?"blocked":"balanced"}
function openPanel(n){["student","counselor","admin"].forEach(x=>{document.getElementById(x+"Panel").classList.toggle("active",x===n);document.getElementById("tab"+x[0].toUpperCase()+x.slice(1)).classList.toggle("active",x===n)});document.getElementById("system").scrollIntoView({behavior:"smooth"})}
function runAI(){let f=data().filter(s=>s.risk.score!==null&&s.risk.score>=state.settings.medium);state.cases=f.map((s,i)=>({caseId:"CASE-"+(3100+i),studentId:s.id,name:s.name,score:s.risk.score,level:s.risk.level,reasons:s.risk.reasons,decision:"Pending",intervention:"Waiting for counselor review",followup:"Not started"}));log(state.cases.length+" AI risk signal(s) generated. No automatic intervention triggered.")}
function decide(id,d){state.cases=state.cases.map(c=>c.caseId===id?{...c,decision:d,intervention:d==="Level 1"?"Self-help resource pushed":d==="Level 2"?"Warm reminder and appointment suggestion":d==="Level 3"?"Active counselor meeting scheduled":"Monitor only",followup:"Follow-up required"}:c);log("Counselor decision for "+id+": "+d)}
function selectStudent(id){state.selectedId=id;save();renderAll()}
function toggleConsent(){let s=sel();state.students=state.students.map(x=>x.id===s.id?{...x,consent:!x.consent}:x);log(s.id+(s.consent?" withdrew consent":" granted consent"))}
function submitSelfAssessment(){let s=sel(),stress=Number(document.getElementById("stressInput").value||3),sleep=Number(document.getElementById("sleepInput").value||6),mood=document.getElementById("moodInput").value;state.students=state.students.map(x=>x.id===s.id?{...x,stress,sleep}:x);log(s.id+" submitted self-assessment: mood="+mood+", stress="+stress+", sleep="+sleep)}
function deleteStudentData(){let s=sel();state.students=state.students.map(x=>x.id===s.id?{...x,consent:false,lms:0,library:0,dining:0,gym:0,stress:0,sleep:0,social:0}:x);log(s.id+" deleted optional wellness data")}
function downloadStudentData(){download(JSON.stringify(sel(),null,2),sel().id+"_scwis_data.json","application/json");log(sel().id+" downloaded personal data")}
function downloadCSVTemplate(){download("student_id,name,consent,lms_activity,library_visits,dining_count,gym_visits,self_report_stress,sleep_hours,social_activity\nS2001,Jamie Lin,true,86,5,12,3,2,7.1,7\nS2002,Chris Zhao,true,41,0,3,0,5,4.0,1","scwis_template.csv","text/csv")}
function download(t,n,type){let b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
function uploadCSV(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=x=>{let arr=parseCSV(String(x.target.result||""));if(!arr.length){alert("CSV format not recognized.");return}state.students=arr;state.cases=[];state.selectedId=arr[0].id;log(arr.length+" records imported; consent filter applied")};r.readAsText(file)}
function parseCSV(t){let rows=t.trim().split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];let h=rows[0].split(",").map(x=>x.trim());return rows.slice(1).map(row=>{let v=row.split(",").map(x=>x.trim()),o={};h.forEach((x,i)=>o[x]=v[i]);return{id:o.student_id||o.id||"Unknown",name:o.name||"Unnamed Student",consent:["true","yes","1"].includes(String(o.consent).toLowerCase()),lms:Number(o.lms_activity||o.lms||0),library:Number(o.library_visits||o.library||0),dining:Number(o.dining_count||o.dining||0),gym:Number(o.gym_visits||o.gym||0),stress:Number(o.self_report_stress||o.stress||0),sleep:Number(o.sleep_hours||o.sleep||0),social:Number(o.social_activity||o.social||0)}})}
function saveSettings(){state.settings.high=Number(document.getElementById("highThreshold").value||80);state.settings.medium=Number(document.getElementById("mediumThreshold").value||55);log("Admin updated risk thresholds: high="+state.settings.high+", medium="+state.settings.medium)}
function resetDatabase(){state={students:JSON.parse(JSON.stringify(defaults)),cases:[],selectedId:defaults[0].id,logs:["Local database reset","Consent filter initialized","Audit logging enabled"],settings:{high:80,medium:55}};save();renderAll()}
function renderAll(){save();renderStats();renderPreview();renderStudent();renderCases();renderCharts();renderRecords();renderLogs();document.getElementById("highThreshold").value=state.settings.high;document.getElementById("mediumThreshold").value=state.settings.medium}
function renderStats(){let d=data(),cons=state.students.filter(s=>s.consent).length,flag=d.filter(s=>s.risk.score!==null&&s.risk.score>=state.settings.medium),high=d.filter(s=>s.risk.level==="High").length,rev=state.cases.filter(c=>c.decision!=="Pending").length,pend=state.cases.filter(c=>c.decision==="Pending").length,supp=state.cases.filter(c=>["Level 1","Level 2","Level 3"].includes(c.decision)).length;txt("statConsented",cons+"/"+state.students.length);txt("statSignals",flag.length);txt("statReviewed",rev);txt("miniRecords",state.students.length);txt("miniHigh",high);txt("miniPending",pend);txt("dashNeedReview",flag.length);txt("dashPending",pend);txt("dashReviewed",rev);txt("dashSupport",supp)}
function renderPreview(){document.getElementById("previewQueue").innerHTML=data().slice(0,4).map(s=>`<div class="row"><div class="avatar">${s.name[0]}</div><div><strong>${s.name}</strong><span>${s.id} · consent ${s.consent?"yes":"no"}</span></div><span class="pill ${cls(s.risk.tone)}">${s.risk.level}${s.risk.score!==null?" · "+s.risk.score:""}</span></div>`).join("")}
function renderStudent(){let d=data(),s=sel();document.getElementById("studentList").innerHTML=d.map(x=>`<button class="${s.id===x.id?"sel":""}" onclick="selectStudent('${x.id}')">${x.name}</button>`).join("");let b=document.getElementById("consentButton");b.className=s.consent?"danger":"safe";b.textContent=s.consent?"取消授权 Withdraw Consent":"同意授权 Grant Consent";txt("profileAvatar",s.name[0]);txt("profileName",s.name);txt("profileMeta",s.id+" · Consent "+(s.consent?"Granted":"Blocked"));let r=document.getElementById("profileRisk");r.className="pill "+cls(s.risk.tone);r.textContent=s.risk.level+(s.risk.score!==null?" · "+s.risk.score:"");document.getElementById("dataGrid").innerHTML=[["LMS",s.lms],["Library",s.library],["Dining",s.dining],["Gym",s.gym],["Stress",s.stress],["Sleep",s.sleep]].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join("")}
function renderCases(){let el=document.getElementById("caseGrid");if(!state.cases.length){el.innerHTML=`<div class="empty"><b>No active cases</b><span>Run AI detection first.</span></div>`;return}el.innerHTML=state.cases.map(c=>`<div class="case"><small>${c.caseId}</small><h4>${c.name}</h4><span class="pill ${c.level==="High"?"high":"medium"}">${c.level} · ${c.score}</span>${c.reasons.slice(0,3).map(r=>`<p>• ${r}</p>`).join("")}<div class="caseActions"><button onclick="decide('${c.caseId}','Level 1')">Level 1</button><button onclick="decide('${c.caseId}','Level 2')">Level 2</button><button onclick="decide('${c.caseId}','Level 3')">Level 3</button></div><div class="caseActions single"><button onclick="decide('${c.caseId}','Monitor Only')">Monitor Only</button></div><span class="decision">Decision: ${c.decision} · ${c.followup||""}</span></div>`).join("")}
function renderCharts(){renderRiskBar();renderTrend();renderDist()}
function renderRiskBar(){document.getElementById("riskBarChart").innerHTML=data().map(s=>{let v=s.risk.score||0,t="greenB";if(s.risk.level==="High")t="red";else if(s.risk.level==="Medium")t="amber";else if(s.risk.level==="Low")t="cyan";else if(s.risk.level==="Blocked")t="gray";return `<div class="barItem"><div class="barTrack"><div class="barFill ${t}" style="height:${v}%"></div></div><span>${s.id.replace("S","")}</span><b>${v}</b></div>`}).join("")}
function renderTrend(){document.getElementById("trendChart").innerHTML=trend.map(d=>`<div class="trendCol"><div class="trendBars"><div class="trendBar stress" style="height:${d.s*1.55}px"></div><div class="trendBar well" style="height:${d.b*1.55}px"></div></div><span>${d.w}</span></div>`).join("")}
function pie(id,leg,total,vals){let sum=vals.reduce((a,b)=>a+b.value,0)||1,start=0,parts=vals.map(v=>{let end=start+v.value/sum*100,p=`${v.color} ${start}% ${end}%`;start=end;return p});document.getElementById(id).style.background="conic-gradient("+parts.join(",")+")";txt(total,sum);document.getElementById(leg).innerHTML=vals.map(v=>`<div><i style="background:${v.color}"></i>${v.label}: <b>${v.value}</b></div>`).join("")}
function renderDist(){let d=data();pie("riskPie","pieLegend","pieTotal",[{label:"High",value:d.filter(s=>s.risk.level==="High").length,color:"#f43f5e"},{label:"Medium",value:d.filter(s=>s.risk.level==="Medium").length,color:"#f59e0b"},{label:"Low",value:d.filter(s=>s.risk.level==="Low").length,color:"#0ea5e9"},{label:"Balanced",value:d.filter(s=>s.risk.level==="Balanced").length,color:"#10b981"},{label:"Blocked",value:d.filter(s=>s.risk.level==="Blocked").length,color:"#94a3b8"}]);pie("interventionPie","interventionLegend","interventionTotal",[{label:"Pending",value:state.cases.filter(c=>c.decision==="Pending").length,color:"#f59e0b"},{label:"L1",value:state.cases.filter(c=>c.decision==="Level 1").length,color:"#10b981"},{label:"L2",value:state.cases.filter(c=>c.decision==="Level 2").length,color:"#0ea5e9"},{label:"L3",value:state.cases.filter(c=>c.decision==="Level 3").length,color:"#ef4444"},{label:"Monitor",value:state.cases.filter(c=>c.decision==="Monitor Only").length,color:"#94a3b8"}])}
function renderRecords(){let q=(document.getElementById("searchInput")?.value||"").toLowerCase(),d=data().filter(s=>(s.id+" "+s.name).toLowerCase().includes(q));document.getElementById("recordsList").innerHTML=d.map(s=>`<div class="record"><div class="avatar darkA">${s.name[0]}</div><div><strong>${s.name}</strong><span>${s.id} · Consent ${s.consent?"Granted":"Blocked"}</span></div><span class="pill ${cls(s.risk.tone)}">${s.risk.level}${s.risk.score!==null?" · "+s.risk.score:""}</span><p>${s.risk.reasons.slice(0,2).join("; ")}</p></div>`).join("")}
function renderLogs(){document.getElementById("logList").innerHTML=state.logs.map(l=>`<div>${l}</div>`).join("")}
renderAll();
